#ifndef ONENET_OTA_H
#define ONENET_OTA_H

#define ONENET_FUSE_HOST "iot-api.heclouds.com"
#define ONENET_HTTP_PORT 80

#define ONENET_PRODUCT_ID "OmZ40ZapAD"
#define ONENET_DEVICE_NAME "STM32F407VGT6_SKYSTAR"
#define ONENET_CURRENT_VERSION "V1.0"

#define ONENET_ACCESS_KEY_B64 "0edef2e927d242a5bc8d154160cd70e1"
#define ONENET_AUTH_FUSE_VER "2022-05-01"
#define ONENET_AUTH_FUSE_RES_RAW "userid/510792"
#define ONENET_AUTH_METHOD "sha1"
#define ONENET_AUTH_UNIX_NOW_BASE 1774170000UL
#define ONENET_AUTH_ET_TTL_SEC 3600UL

#define ONENET_DOWNLOAD_CHUNK_SIZE 1024U
#define ONENET_PROGRESS_STEP_PCT 10U

void ONENET_OTA_SetTaskId(const char *tid);
void ONENET_OTA_ProcessUpgrade(void);

#endif
